### ISSUE TITLE
Plugin updates

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-attrs-parser#4]
@maltsev @Scrum I'd like to work on a major release for this plugin if you're OK with it:

- ESM, no build step
- update dependencies
- update build and ci
- `stringifyAttr || true` in `parser.es6` so it doesn't quote attributes on its own

Using it in a bunch of plugins and in Maizzle, it has been really useful 🙏

**Comment by Scrum** [comment]
@cossssmin Great idea, I'm all for it

**Comment by maltsev** [comment]
@cossssmin wow, that would be awesome! Thanks!

**Comment by cossssmin** [comment]
Thanks, will work on it and open a PR 👍
